export const milkProducts = [
    { name: "Sữa chua 300ml không đường", price: "20000", loại: "sữa chua" },
    { name: "Sữa chua 300ml có đường", price: "21000", loại: "sữa chua" },
    { name: "Sữa tươi 1L không đường", price: "35000", loại: "sữa tươi" },
    { name: "Sữa tươi 1L có đường", price: "36000", loại: "sữa tươi" },
    { name: "Sữa đặc 380g có đường", price: "25000", loại: "sữa đặc" },
    { name: "Sữa đặc 380g không đường", price: "24000", loại: "sữa đặc" },
    { name: "Sữa đậu nành 250ml", price: "15000", loại: "sữa đậu nành" },
    { name: "Sữa đậu nành 500ml", price: "20000", loại: "sữa đậu nành" },
    { name: "Sữa chua uống vị dâu 180ml", price: "12000", loại: "sữa chua uống" },
    { name: "Sữa chua uống vị cam 180ml", price: "12000", loại: "sữa chua uống" },
    { name: "Sữa bắp 300ml", price: "17000", loại: "sữa bắp" },
    { name: "Sữa bắp 500ml", price: "22000", loại: "sữa bắp" },
    { name: "Sữa hạnh nhân 1L", price: "45000", loại: "sữa hạt" },
    { name: "Sữa óc chó 1L", price: "46000", loại: "sữa hạt" },
    { name: "Sữa chua Hy Lạp 100ml", price: "18000", loại: "sữa chua" },
    { name: "Sữa tươi tiệt trùng 180ml", price: "11000", loại: "sữa tươi" },
    { name: "Sữa tiệt trùng vị socola 180ml", price: "13000", loại: "sữa tươi" },
    { name: "Sữa tươi vị dâu 180ml", price: "13000", loại: "sữa tươi" },
    { name: "Sữa tươi tách béo 1L", price: "37000", loại: "sữa tươi" },
    { name: "Sữa tươi nguyên kem 1L", price: "39000", loại: "sữa tươi" },
    { name: "Sữa tươi thanh trùng 500ml", price: "28000", loại: "sữa tươi" },
    { name: "Sữa đặc vị socola 380g", price: "26000", loại: "sữa đặc" },
    { name: "Sữa đặc vị cà phê 380g", price: "27000", loại: "sữa đặc" },
    {
      name: "Sữa chua uống men sống 180ml",
      price: "15000",
      loại: "sữa chua uống",
    },
    { name: "Sữa chua nếp cẩm 100ml", price: "14000", loại: "sữa chua" },
    { name: "Sữa chua nha đam 100ml", price: "14000", loại: "sữa chua" },
    { name: "Sữa tươi 180ml có đường", price: "11000", loại: "sữa tươi" },
    { name: "Sữa tươi 180ml không đường", price: "10500", loại: "sữa tươi" },
    { name: "Sữa bắp nếp 500ml", price: "23000", loại: "sữa bắp" },
    { name: "Sữa đậu xanh 300ml", price: "16000", loại: "sữa đậu nành" },
    { name: "Sữa mè đen 300ml", price: "18000", loại: "sữa hạt" },
    { name: "Sữa hạnh nhân vị vani 1L", price: "46000", loại: "sữa hạt" },
    { name: "Sữa óc chó vị dâu 1L", price: "47000", loại: "sữa hạt" },
    { name: "Sữa đặc Hàn Quốc 380g", price: "29000", loại: "sữa đặc" },
    { name: "Sữa chua Hy Lạp vị xoài 100ml", price: "19000", loại: "sữa chua" },
    {name: "Sữa chua Hy Lạp vị việt quất 100ml", price: "19000",  loại: "sữa chua",   },
    { name: "Sữa đậu nành nguyên chất 1L", price: "30000", loại: "sữa đậu nành" },
    {
      name: "Sữa đậu nành hương lá dứa 300ml",
      price: "17000",
      loại: "sữa đậu nành",
    },
    {
      name: "Sữa chua uống vị việt quất 180ml",
      price: "13000",
      loại: "sữa chua uống",
    },
    { name: "Sữa tươi vị vani 180ml", price: "12500", loại: "sữa tươi" },
    { name: "Sữa bắp nguyên chất 1L", price: "32000", loại: "sữa bắp" },
    {
      name: "Sữa chua uống probi vị cam 180ml",
      price: "14000",
      loại: "sữa chua uống",
    },
    { name: "Sữa đặc có đường 1kg", price: "58000", loại: "sữa đặc" },
    { name: "Sữa đặc 500g không đường", price: "32000", loại: "sữa đặc" },
    { name: "Sữa đặc pha cà phê 300g", price: "23000", loại: "sữa đặc" },
    {
      name: "Sữa chua uống probi vị nho 180ml",
      price: "14000",
      loại: "sữa chua uống",
    },
    { name: "Sữa chua vị nha đam 100ml", price: "14000", loại: "sữa chua" },
    {
      name: "Sữa chua uống vị dưa gang 180ml",
      price: "13500",
      loại: "sữa chua uống",
    },
    {
      name: "Sữa chua uống vị kiwi 180ml",
      price: "13500",
      loại: "sữa chua uống",
    },
    {
      name: "Sữa chua uống vị xoài 180ml",
      price: "13500",
      loại: "sữa chua uống",
    },
    {
      name: "Sữa tươi tiệt trùng có đường 500ml",
      price: "22000",
      loại: "sữa tươi",
    },
    {
      name: "Sữa tươi thanh trùng không đường 1L",
      price: "36000",
      loại: "sữa tươi",
    },
    {
      name: "Sữa chua uống probi vị táo 180ml",
      price: "14000",
      loại: "sữa chua uống",
    },
    {
      name: "Sữa đậu nành vị hạt sen 300ml",
      price: "18000",
      loại: "sữa đậu nành",
    },
    {
      name: "Sữa chua trân châu đường đen 100ml",
      price: "17000",
      loại: "sữa chua",
    },
    { name: "Sữa đặc Thái Lan 380g", price: "27000", loại: "sữa đặc" },
    { name: "Sữa chua vị dâu 100ml", price: "13000", loại: "sữa chua" },
    { name: "Sữa hạt dẻ cười 1L", price: "48000", loại: "sữa hạt" },
    { name: "Sữa hạnh nhân nguyên chất 500ml", price: "25000", loại: "sữa hạt" },
    {
      name: "Sữa chua uống probi vị sữa 180ml",
      price: "13000",
      loại: "sữa chua uống",
    },
    { name: "Sữa tươi thanh trùng ít béo 1L", price: "37000", loại: "sữa tươi" },
    { name: "Sữa đặc kem béo 380g", price: "28000", loại: "sữa đặc" },
    {
      name: "Sữa chua uống vị sữa chua 180ml",
      price: "12500",
      loại: "sữa chua uống",
    },
    { name: "Sữa chua uống vị đào 180ml", price: "13500", loại: "sữa chua uống" },
]